-- hit_stack_system_run_control_splitter_0.vhd

-- Generated using ACDS version 18.1 625

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hit_stack_system_run_control_splitter_0 is
	generic (
		NUMBER_OF_OUTPUTS : integer := 6;
		QUALIFY_VALID_OUT : integer := 0;
		USE_PACKETS       : integer := 0;
		DATA_WIDTH        : integer := 9;
		CHANNEL_WIDTH     : integer := 1;
		ERROR_WIDTH       : integer := 1;
		BITS_PER_SYMBOL   : integer := 9;
		EMPTY_WIDTH       : integer := 1
	);
	port (
		clk                 : in  std_logic                    := '0';             --   clk.clk
		reset               : in  std_logic                    := '0';             -- reset.reset
		in0_ready           : out std_logic;                                       --    in.ready
		in0_valid           : in  std_logic                    := '0';             --      .valid
		in0_data            : in  std_logic_vector(8 downto 0) := (others => '0'); --      .data
		out0_ready          : in  std_logic                    := '0';             --  out0.ready
		out0_valid          : out std_logic;                                       --      .valid
		out0_data           : out std_logic_vector(8 downto 0);                    --      .data
		out1_ready          : in  std_logic                    := '0';             --  out1.ready
		out1_valid          : out std_logic;                                       --      .valid
		out1_data           : out std_logic_vector(8 downto 0);                    --      .data
		out2_ready          : in  std_logic                    := '0';             --  out2.ready
		out2_valid          : out std_logic;                                       --      .valid
		out2_data           : out std_logic_vector(8 downto 0);                    --      .data
		out3_ready          : in  std_logic                    := '0';             --  out3.ready
		out3_valid          : out std_logic;                                       --      .valid
		out3_data           : out std_logic_vector(8 downto 0);                    --      .data
		out4_ready          : in  std_logic                    := '0';             --  out4.ready
		out4_valid          : out std_logic;                                       --      .valid
		out4_data           : out std_logic_vector(8 downto 0);                    --      .data
		out5_ready          : in  std_logic                    := '0';             --  out5.ready
		out5_valid          : out std_logic;                                       --      .valid
		out5_data           : out std_logic_vector(8 downto 0);                    --      .data
		in0_channel         : in  std_logic_vector(0 downto 0) := (others => '0');
		in0_empty           : in  std_logic_vector(0 downto 0) := (others => '0');
		in0_endofpacket     : in  std_logic                    := '0';
		in0_error           : in  std_logic_vector(0 downto 0) := (others => '0');
		in0_startofpacket   : in  std_logic                    := '0';
		out0_channel        : out std_logic_vector(0 downto 0);
		out0_empty          : out std_logic_vector(0 downto 0);
		out0_endofpacket    : out std_logic;
		out0_error          : out std_logic_vector(0 downto 0);
		out0_startofpacket  : out std_logic;
		out10_channel       : out std_logic_vector(0 downto 0);
		out10_data          : out std_logic_vector(8 downto 0);
		out10_empty         : out std_logic_vector(0 downto 0);
		out10_endofpacket   : out std_logic;
		out10_error         : out std_logic_vector(0 downto 0);
		out10_ready         : in  std_logic                    := '0';
		out10_startofpacket : out std_logic;
		out10_valid         : out std_logic;
		out11_channel       : out std_logic_vector(0 downto 0);
		out11_data          : out std_logic_vector(8 downto 0);
		out11_empty         : out std_logic_vector(0 downto 0);
		out11_endofpacket   : out std_logic;
		out11_error         : out std_logic_vector(0 downto 0);
		out11_ready         : in  std_logic                    := '0';
		out11_startofpacket : out std_logic;
		out11_valid         : out std_logic;
		out12_channel       : out std_logic_vector(0 downto 0);
		out12_data          : out std_logic_vector(8 downto 0);
		out12_empty         : out std_logic_vector(0 downto 0);
		out12_endofpacket   : out std_logic;
		out12_error         : out std_logic_vector(0 downto 0);
		out12_ready         : in  std_logic                    := '0';
		out12_startofpacket : out std_logic;
		out12_valid         : out std_logic;
		out13_channel       : out std_logic_vector(0 downto 0);
		out13_data          : out std_logic_vector(8 downto 0);
		out13_empty         : out std_logic_vector(0 downto 0);
		out13_endofpacket   : out std_logic;
		out13_error         : out std_logic_vector(0 downto 0);
		out13_ready         : in  std_logic                    := '0';
		out13_startofpacket : out std_logic;
		out13_valid         : out std_logic;
		out14_channel       : out std_logic_vector(0 downto 0);
		out14_data          : out std_logic_vector(8 downto 0);
		out14_empty         : out std_logic_vector(0 downto 0);
		out14_endofpacket   : out std_logic;
		out14_error         : out std_logic_vector(0 downto 0);
		out14_ready         : in  std_logic                    := '0';
		out14_startofpacket : out std_logic;
		out14_valid         : out std_logic;
		out15_channel       : out std_logic_vector(0 downto 0);
		out15_data          : out std_logic_vector(8 downto 0);
		out15_empty         : out std_logic_vector(0 downto 0);
		out15_endofpacket   : out std_logic;
		out15_error         : out std_logic_vector(0 downto 0);
		out15_ready         : in  std_logic                    := '0';
		out15_startofpacket : out std_logic;
		out15_valid         : out std_logic;
		out1_channel        : out std_logic_vector(0 downto 0);
		out1_empty          : out std_logic_vector(0 downto 0);
		out1_endofpacket    : out std_logic;
		out1_error          : out std_logic_vector(0 downto 0);
		out1_startofpacket  : out std_logic;
		out2_channel        : out std_logic_vector(0 downto 0);
		out2_empty          : out std_logic_vector(0 downto 0);
		out2_endofpacket    : out std_logic;
		out2_error          : out std_logic_vector(0 downto 0);
		out2_startofpacket  : out std_logic;
		out3_channel        : out std_logic_vector(0 downto 0);
		out3_empty          : out std_logic_vector(0 downto 0);
		out3_endofpacket    : out std_logic;
		out3_error          : out std_logic_vector(0 downto 0);
		out3_startofpacket  : out std_logic;
		out4_channel        : out std_logic_vector(0 downto 0);
		out4_empty          : out std_logic_vector(0 downto 0);
		out4_endofpacket    : out std_logic;
		out4_error          : out std_logic_vector(0 downto 0);
		out4_startofpacket  : out std_logic;
		out5_channel        : out std_logic_vector(0 downto 0);
		out5_empty          : out std_logic_vector(0 downto 0);
		out5_endofpacket    : out std_logic;
		out5_error          : out std_logic_vector(0 downto 0);
		out5_startofpacket  : out std_logic;
		out6_channel        : out std_logic_vector(0 downto 0);
		out6_data           : out std_logic_vector(8 downto 0);
		out6_empty          : out std_logic_vector(0 downto 0);
		out6_endofpacket    : out std_logic;
		out6_error          : out std_logic_vector(0 downto 0);
		out6_ready          : in  std_logic                    := '0';
		out6_startofpacket  : out std_logic;
		out6_valid          : out std_logic;
		out7_channel        : out std_logic_vector(0 downto 0);
		out7_data           : out std_logic_vector(8 downto 0);
		out7_empty          : out std_logic_vector(0 downto 0);
		out7_endofpacket    : out std_logic;
		out7_error          : out std_logic_vector(0 downto 0);
		out7_ready          : in  std_logic                    := '0';
		out7_startofpacket  : out std_logic;
		out7_valid          : out std_logic;
		out8_channel        : out std_logic_vector(0 downto 0);
		out8_data           : out std_logic_vector(8 downto 0);
		out8_empty          : out std_logic_vector(0 downto 0);
		out8_endofpacket    : out std_logic;
		out8_error          : out std_logic_vector(0 downto 0);
		out8_ready          : in  std_logic                    := '0';
		out8_startofpacket  : out std_logic;
		out8_valid          : out std_logic;
		out9_channel        : out std_logic_vector(0 downto 0);
		out9_data           : out std_logic_vector(8 downto 0);
		out9_empty          : out std_logic_vector(0 downto 0);
		out9_endofpacket    : out std_logic;
		out9_error          : out std_logic_vector(0 downto 0);
		out9_ready          : in  std_logic                    := '0';
		out9_startofpacket  : out std_logic;
		out9_valid          : out std_logic
	);
end entity hit_stack_system_run_control_splitter_0;

architecture rtl of hit_stack_system_run_control_splitter_0 is
	component altera_avalon_st_splitter is
		generic (
			NUMBER_OF_OUTPUTS : integer := 2;
			QUALIFY_VALID_OUT : integer := 1;
			USE_PACKETS       : integer := 0;
			DATA_WIDTH        : integer := 8;
			CHANNEL_WIDTH     : integer := 1;
			ERROR_WIDTH       : integer := 1;
			BITS_PER_SYMBOL   : integer := 8;
			EMPTY_WIDTH       : integer := 1
		);
		port (
			clk                 : in  std_logic                    := 'X';             -- clk
			reset               : in  std_logic                    := 'X';             -- reset
			in0_ready           : out std_logic;                                       -- ready
			in0_valid           : in  std_logic                    := 'X';             -- valid
			in0_data            : in  std_logic_vector(8 downto 0) := (others => 'X'); -- data
			out0_ready          : in  std_logic                    := 'X';             -- ready
			out0_valid          : out std_logic;                                       -- valid
			out0_data           : out std_logic_vector(8 downto 0);                    -- data
			out1_ready          : in  std_logic                    := 'X';             -- ready
			out1_valid          : out std_logic;                                       -- valid
			out1_data           : out std_logic_vector(8 downto 0);                    -- data
			out2_ready          : in  std_logic                    := 'X';             -- ready
			out2_valid          : out std_logic;                                       -- valid
			out2_data           : out std_logic_vector(8 downto 0);                    -- data
			out3_ready          : in  std_logic                    := 'X';             -- ready
			out3_valid          : out std_logic;                                       -- valid
			out3_data           : out std_logic_vector(8 downto 0);                    -- data
			out4_ready          : in  std_logic                    := 'X';             -- ready
			out4_valid          : out std_logic;                                       -- valid
			out4_data           : out std_logic_vector(8 downto 0);                    -- data
			out5_ready          : in  std_logic                    := 'X';             -- ready
			out5_valid          : out std_logic;                                       -- valid
			out5_data           : out std_logic_vector(8 downto 0);                    -- data
			in0_startofpacket   : in  std_logic                    := 'X';             -- startofpacket
			in0_endofpacket     : in  std_logic                    := 'X';             -- endofpacket
			in0_empty           : in  std_logic_vector(0 downto 0) := (others => 'X'); -- empty
			in0_channel         : in  std_logic_vector(0 downto 0) := (others => 'X'); -- channel
			in0_error           : in  std_logic_vector(0 downto 0) := (others => 'X'); -- error
			out0_startofpacket  : out std_logic;                                       -- startofpacket
			out0_endofpacket    : out std_logic;                                       -- endofpacket
			out0_empty          : out std_logic_vector(0 downto 0);                    -- empty
			out0_channel        : out std_logic_vector(0 downto 0);                    -- channel
			out0_error          : out std_logic_vector(0 downto 0);                    -- error
			out1_startofpacket  : out std_logic;                                       -- startofpacket
			out1_endofpacket    : out std_logic;                                       -- endofpacket
			out1_empty          : out std_logic_vector(0 downto 0);                    -- empty
			out1_channel        : out std_logic_vector(0 downto 0);                    -- channel
			out1_error          : out std_logic_vector(0 downto 0);                    -- error
			out2_startofpacket  : out std_logic;                                       -- startofpacket
			out2_endofpacket    : out std_logic;                                       -- endofpacket
			out2_empty          : out std_logic_vector(0 downto 0);                    -- empty
			out2_channel        : out std_logic_vector(0 downto 0);                    -- channel
			out2_error          : out std_logic_vector(0 downto 0);                    -- error
			out3_startofpacket  : out std_logic;                                       -- startofpacket
			out3_endofpacket    : out std_logic;                                       -- endofpacket
			out3_empty          : out std_logic_vector(0 downto 0);                    -- empty
			out3_channel        : out std_logic_vector(0 downto 0);                    -- channel
			out3_error          : out std_logic_vector(0 downto 0);                    -- error
			out4_startofpacket  : out std_logic;                                       -- startofpacket
			out4_endofpacket    : out std_logic;                                       -- endofpacket
			out4_empty          : out std_logic_vector(0 downto 0);                    -- empty
			out4_channel        : out std_logic_vector(0 downto 0);                    -- channel
			out4_error          : out std_logic_vector(0 downto 0);                    -- error
			out5_startofpacket  : out std_logic;                                       -- startofpacket
			out5_endofpacket    : out std_logic;                                       -- endofpacket
			out5_empty          : out std_logic_vector(0 downto 0);                    -- empty
			out5_channel        : out std_logic_vector(0 downto 0);                    -- channel
			out5_error          : out std_logic_vector(0 downto 0);                    -- error
			out6_ready          : in  std_logic                    := 'X';             -- ready
			out6_valid          : out std_logic;                                       -- valid
			out6_startofpacket  : out std_logic;                                       -- startofpacket
			out6_endofpacket    : out std_logic;                                       -- endofpacket
			out6_empty          : out std_logic_vector(0 downto 0);                    -- empty
			out6_channel        : out std_logic_vector(0 downto 0);                    -- channel
			out6_error          : out std_logic_vector(0 downto 0);                    -- error
			out6_data           : out std_logic_vector(8 downto 0);                    -- data
			out7_ready          : in  std_logic                    := 'X';             -- ready
			out7_valid          : out std_logic;                                       -- valid
			out7_startofpacket  : out std_logic;                                       -- startofpacket
			out7_endofpacket    : out std_logic;                                       -- endofpacket
			out7_empty          : out std_logic_vector(0 downto 0);                    -- empty
			out7_channel        : out std_logic_vector(0 downto 0);                    -- channel
			out7_error          : out std_logic_vector(0 downto 0);                    -- error
			out7_data           : out std_logic_vector(8 downto 0);                    -- data
			out8_ready          : in  std_logic                    := 'X';             -- ready
			out8_valid          : out std_logic;                                       -- valid
			out8_startofpacket  : out std_logic;                                       -- startofpacket
			out8_endofpacket    : out std_logic;                                       -- endofpacket
			out8_empty          : out std_logic_vector(0 downto 0);                    -- empty
			out8_channel        : out std_logic_vector(0 downto 0);                    -- channel
			out8_error          : out std_logic_vector(0 downto 0);                    -- error
			out8_data           : out std_logic_vector(8 downto 0);                    -- data
			out9_ready          : in  std_logic                    := 'X';             -- ready
			out9_valid          : out std_logic;                                       -- valid
			out9_startofpacket  : out std_logic;                                       -- startofpacket
			out9_endofpacket    : out std_logic;                                       -- endofpacket
			out9_empty          : out std_logic_vector(0 downto 0);                    -- empty
			out9_channel        : out std_logic_vector(0 downto 0);                    -- channel
			out9_error          : out std_logic_vector(0 downto 0);                    -- error
			out9_data           : out std_logic_vector(8 downto 0);                    -- data
			out10_ready         : in  std_logic                    := 'X';             -- ready
			out10_valid         : out std_logic;                                       -- valid
			out10_startofpacket : out std_logic;                                       -- startofpacket
			out10_endofpacket   : out std_logic;                                       -- endofpacket
			out10_empty         : out std_logic_vector(0 downto 0);                    -- empty
			out10_channel       : out std_logic_vector(0 downto 0);                    -- channel
			out10_error         : out std_logic_vector(0 downto 0);                    -- error
			out10_data          : out std_logic_vector(8 downto 0);                    -- data
			out11_ready         : in  std_logic                    := 'X';             -- ready
			out11_valid         : out std_logic;                                       -- valid
			out11_startofpacket : out std_logic;                                       -- startofpacket
			out11_endofpacket   : out std_logic;                                       -- endofpacket
			out11_empty         : out std_logic_vector(0 downto 0);                    -- empty
			out11_channel       : out std_logic_vector(0 downto 0);                    -- channel
			out11_error         : out std_logic_vector(0 downto 0);                    -- error
			out11_data          : out std_logic_vector(8 downto 0);                    -- data
			out12_ready         : in  std_logic                    := 'X';             -- ready
			out12_valid         : out std_logic;                                       -- valid
			out12_startofpacket : out std_logic;                                       -- startofpacket
			out12_endofpacket   : out std_logic;                                       -- endofpacket
			out12_empty         : out std_logic_vector(0 downto 0);                    -- empty
			out12_channel       : out std_logic_vector(0 downto 0);                    -- channel
			out12_error         : out std_logic_vector(0 downto 0);                    -- error
			out12_data          : out std_logic_vector(8 downto 0);                    -- data
			out13_ready         : in  std_logic                    := 'X';             -- ready
			out13_valid         : out std_logic;                                       -- valid
			out13_startofpacket : out std_logic;                                       -- startofpacket
			out13_endofpacket   : out std_logic;                                       -- endofpacket
			out13_empty         : out std_logic_vector(0 downto 0);                    -- empty
			out13_channel       : out std_logic_vector(0 downto 0);                    -- channel
			out13_error         : out std_logic_vector(0 downto 0);                    -- error
			out13_data          : out std_logic_vector(8 downto 0);                    -- data
			out14_ready         : in  std_logic                    := 'X';             -- ready
			out14_valid         : out std_logic;                                       -- valid
			out14_startofpacket : out std_logic;                                       -- startofpacket
			out14_endofpacket   : out std_logic;                                       -- endofpacket
			out14_empty         : out std_logic_vector(0 downto 0);                    -- empty
			out14_channel       : out std_logic_vector(0 downto 0);                    -- channel
			out14_error         : out std_logic_vector(0 downto 0);                    -- error
			out14_data          : out std_logic_vector(8 downto 0);                    -- data
			out15_ready         : in  std_logic                    := 'X';             -- ready
			out15_valid         : out std_logic;                                       -- valid
			out15_startofpacket : out std_logic;                                       -- startofpacket
			out15_endofpacket   : out std_logic;                                       -- endofpacket
			out15_empty         : out std_logic_vector(0 downto 0);                    -- empty
			out15_channel       : out std_logic_vector(0 downto 0);                    -- channel
			out15_error         : out std_logic_vector(0 downto 0);                    -- error
			out15_data          : out std_logic_vector(8 downto 0)                     -- data
		);
	end component altera_avalon_st_splitter;

begin

	number_of_outputs_check : if NUMBER_OF_OUTPUTS /= 6 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	qualify_valid_out_check : if QUALIFY_VALID_OUT /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	use_packets_check : if USE_PACKETS /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	data_width_check : if DATA_WIDTH /= 9 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	channel_width_check : if CHANNEL_WIDTH /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	error_width_check : if ERROR_WIDTH /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	bits_per_symbol_check : if BITS_PER_SYMBOL /= 9 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	empty_width_check : if EMPTY_WIDTH /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	run_control_splitter_0 : component altera_avalon_st_splitter
		generic map (
			NUMBER_OF_OUTPUTS => 6,
			QUALIFY_VALID_OUT => 0,
			USE_PACKETS       => 0,
			DATA_WIDTH        => 9,
			CHANNEL_WIDTH     => 1,
			ERROR_WIDTH       => 1,
			BITS_PER_SYMBOL   => 9,
			EMPTY_WIDTH       => 1
		)
		port map (
			clk                 => clk,        --   clk.clk
			reset               => reset,      -- reset.reset
			in0_ready           => in0_ready,  --    in.ready
			in0_valid           => in0_valid,  --      .valid
			in0_data            => in0_data,   --      .data
			out0_ready          => out0_ready, --  out0.ready
			out0_valid          => out0_valid, --      .valid
			out0_data           => out0_data,  --      .data
			out1_ready          => out1_ready, --  out1.ready
			out1_valid          => out1_valid, --      .valid
			out1_data           => out1_data,  --      .data
			out2_ready          => out2_ready, --  out2.ready
			out2_valid          => out2_valid, --      .valid
			out2_data           => out2_data,  --      .data
			out3_ready          => out3_ready, --  out3.ready
			out3_valid          => out3_valid, --      .valid
			out3_data           => out3_data,  --      .data
			out4_ready          => out4_ready, --  out4.ready
			out4_valid          => out4_valid, --      .valid
			out4_data           => out4_data,  --      .data
			out5_ready          => out5_ready, --  out5.ready
			out5_valid          => out5_valid, --      .valid
			out5_data           => out5_data,  --      .data
			in0_startofpacket   => '0',        -- (terminated)
			in0_endofpacket     => '0',        -- (terminated)
			in0_empty           => "0",        -- (terminated)
			in0_channel         => "0",        -- (terminated)
			in0_error           => "0",        -- (terminated)
			out0_startofpacket  => open,       -- (terminated)
			out0_endofpacket    => open,       -- (terminated)
			out0_empty          => open,       -- (terminated)
			out0_channel        => open,       -- (terminated)
			out0_error          => open,       -- (terminated)
			out1_startofpacket  => open,       -- (terminated)
			out1_endofpacket    => open,       -- (terminated)
			out1_empty          => open,       -- (terminated)
			out1_channel        => open,       -- (terminated)
			out1_error          => open,       -- (terminated)
			out2_startofpacket  => open,       -- (terminated)
			out2_endofpacket    => open,       -- (terminated)
			out2_empty          => open,       -- (terminated)
			out2_channel        => open,       -- (terminated)
			out2_error          => open,       -- (terminated)
			out3_startofpacket  => open,       -- (terminated)
			out3_endofpacket    => open,       -- (terminated)
			out3_empty          => open,       -- (terminated)
			out3_channel        => open,       -- (terminated)
			out3_error          => open,       -- (terminated)
			out4_startofpacket  => open,       -- (terminated)
			out4_endofpacket    => open,       -- (terminated)
			out4_empty          => open,       -- (terminated)
			out4_channel        => open,       -- (terminated)
			out4_error          => open,       -- (terminated)
			out5_startofpacket  => open,       -- (terminated)
			out5_endofpacket    => open,       -- (terminated)
			out5_empty          => open,       -- (terminated)
			out5_channel        => open,       -- (terminated)
			out5_error          => open,       -- (terminated)
			out6_ready          => '1',        -- (terminated)
			out6_valid          => open,       -- (terminated)
			out6_startofpacket  => open,       -- (terminated)
			out6_endofpacket    => open,       -- (terminated)
			out6_empty          => open,       -- (terminated)
			out6_channel        => open,       -- (terminated)
			out6_error          => open,       -- (terminated)
			out6_data           => open,       -- (terminated)
			out7_ready          => '1',        -- (terminated)
			out7_valid          => open,       -- (terminated)
			out7_startofpacket  => open,       -- (terminated)
			out7_endofpacket    => open,       -- (terminated)
			out7_empty          => open,       -- (terminated)
			out7_channel        => open,       -- (terminated)
			out7_error          => open,       -- (terminated)
			out7_data           => open,       -- (terminated)
			out8_ready          => '1',        -- (terminated)
			out8_valid          => open,       -- (terminated)
			out8_startofpacket  => open,       -- (terminated)
			out8_endofpacket    => open,       -- (terminated)
			out8_empty          => open,       -- (terminated)
			out8_channel        => open,       -- (terminated)
			out8_error          => open,       -- (terminated)
			out8_data           => open,       -- (terminated)
			out9_ready          => '1',        -- (terminated)
			out9_valid          => open,       -- (terminated)
			out9_startofpacket  => open,       -- (terminated)
			out9_endofpacket    => open,       -- (terminated)
			out9_empty          => open,       -- (terminated)
			out9_channel        => open,       -- (terminated)
			out9_error          => open,       -- (terminated)
			out9_data           => open,       -- (terminated)
			out10_ready         => '1',        -- (terminated)
			out10_valid         => open,       -- (terminated)
			out10_startofpacket => open,       -- (terminated)
			out10_endofpacket   => open,       -- (terminated)
			out10_empty         => open,       -- (terminated)
			out10_channel       => open,       -- (terminated)
			out10_error         => open,       -- (terminated)
			out10_data          => open,       -- (terminated)
			out11_ready         => '1',        -- (terminated)
			out11_valid         => open,       -- (terminated)
			out11_startofpacket => open,       -- (terminated)
			out11_endofpacket   => open,       -- (terminated)
			out11_empty         => open,       -- (terminated)
			out11_channel       => open,       -- (terminated)
			out11_error         => open,       -- (terminated)
			out11_data          => open,       -- (terminated)
			out12_ready         => '1',        -- (terminated)
			out12_valid         => open,       -- (terminated)
			out12_startofpacket => open,       -- (terminated)
			out12_endofpacket   => open,       -- (terminated)
			out12_empty         => open,       -- (terminated)
			out12_channel       => open,       -- (terminated)
			out12_error         => open,       -- (terminated)
			out12_data          => open,       -- (terminated)
			out13_ready         => '1',        -- (terminated)
			out13_valid         => open,       -- (terminated)
			out13_startofpacket => open,       -- (terminated)
			out13_endofpacket   => open,       -- (terminated)
			out13_empty         => open,       -- (terminated)
			out13_channel       => open,       -- (terminated)
			out13_error         => open,       -- (terminated)
			out13_data          => open,       -- (terminated)
			out14_ready         => '1',        -- (terminated)
			out14_valid         => open,       -- (terminated)
			out14_startofpacket => open,       -- (terminated)
			out14_endofpacket   => open,       -- (terminated)
			out14_empty         => open,       -- (terminated)
			out14_channel       => open,       -- (terminated)
			out14_error         => open,       -- (terminated)
			out14_data          => open,       -- (terminated)
			out15_ready         => '1',        -- (terminated)
			out15_valid         => open,       -- (terminated)
			out15_startofpacket => open,       -- (terminated)
			out15_endofpacket   => open,       -- (terminated)
			out15_empty         => open,       -- (terminated)
			out15_channel       => open,       -- (terminated)
			out15_error         => open,       -- (terminated)
			out15_data          => open        -- (terminated)
		);

end architecture rtl; -- of hit_stack_system_run_control_splitter_0
